
#- Carsten's PDK. Borders, symbols, loop stability
cpdk:
  remote: git@github.com:wulffern/cpdk.git
  revision: main


tech_sky130B:
  remote: git@github.com:wulffern/tech_sky130B.git
  revision: main
